/*
 * Copyright (c) 2018 Oracle and/or its affiliates. All rights reserved.
 *
 * This program and the accompanying materials are made available under the
 * terms of the Eclipse Public License v. 2.0, which is available at
 * http://www.eclipse.org/legal/epl-2.0.
 *
 * This Source Code may also be made available under the following Secondary
 * Licenses when the conditions for such availability set forth in the
 * Eclipse Public License v. 2.0 are satisfied: GNU General Public License,
 * version 2 with the GNU Classpath Exception, which is available at
 * https://www.gnu.org/software/classpath/license.html.
 *
 * SPDX-License-Identifier: EPL-2.0 OR GPL-2.0 WITH Classpath-exception-2.0
 */
 
/* Generated By:JavaCC: Do not edit this line. ELParserTreeConstants.java Version 5.0 */
package com.sun.el.parser;

public interface ELParserTreeConstants
{
  public int JJTCOMPOSITEEXPRESSION = 0;
  public int JJTLITERALEXPRESSION = 1;
  public int JJTDEFERREDEXPRESSION = 2;
  public int JJTDYNAMICEXPRESSION = 3;
  public int JJTVOID = 4;
  public int JJTSEMICOLON = 5;
  public int JJTASSIGN = 6;
  public int JJTLAMBDAEXPRESSION = 7;
  public int JJTLAMBDAPARAMETERS = 8;
  public int JJTCHOICE = 9;
  public int JJTOR = 10;
  public int JJTAND = 11;
  public int JJTEQUAL = 12;
  public int JJTNOTEQUAL = 13;
  public int JJTLESSTHAN = 14;
  public int JJTGREATERTHAN = 15;
  public int JJTLESSTHANEQUAL = 16;
  public int JJTGREATERTHANEQUAL = 17;
  public int JJTCONCAT = 18;
  public int JJTPLUS = 19;
  public int JJTMINUS = 20;
  public int JJTMULT = 21;
  public int JJTDIV = 22;
  public int JJTMOD = 23;
  public int JJTNEGATIVE = 24;
  public int JJTNOT = 25;
  public int JJTEMPTY = 26;
  public int JJTVALUE = 27;
  public int JJTDOTSUFFIX = 28;
  public int JJTBRACKETSUFFIX = 29;
  public int JJTMETHODARGUMENTS = 30;
  public int JJTMAPDATA = 31;
  public int JJTMAPENTRY = 32;
  public int JJTLISTDATA = 33;
  public int JJTIDENTIFIER = 34;
  public int JJTFUNCTION = 35;
  public int JJTTRUE = 36;
  public int JJTFALSE = 37;
  public int JJTFLOATINGPOINT = 38;
  public int JJTINTEGER = 39;
  public int JJTSTRING = 40;
  public int JJTNULL = 41;


  public String[] jjtNodeName = {
    "CompositeExpression",
    "LiteralExpression",
    "DeferredExpression",
    "DynamicExpression",
    "void",
    "SemiColon",
    "Assign",
    "LambdaExpression",
    "LambdaParameters",
    "Choice",
    "Or",
    "And",
    "Equal",
    "NotEqual",
    "LessThan",
    "GreaterThan",
    "LessThanEqual",
    "GreaterThanEqual",
    "Concat",
    "Plus",
    "Minus",
    "Mult",
    "Div",
    "Mod",
    "Negative",
    "Not",
    "Empty",
    "Value",
    "DotSuffix",
    "BracketSuffix",
    "MethodArguments",
    "MapData",
    "MapEntry",
    "ListData",
    "Identifier",
    "Function",
    "True",
    "False",
    "FloatingPoint",
    "Integer",
    "String",
    "Null",
  };
}
/* JavaCC - OriginalChecksum=295bae338407e43a1d349f1ce802614a (do not edit this line) */
